# CCAGI Configuration v1.0
# Customer Cloud AGI - 完全自律型AIエージェントシステム

# プロジェクト名（init時に自動設定）
project_name: "taskflow"
version: "1.0.0"
description: "TaskFlow - タスク管理アプリケーション"

# ========================================
# 外部依存設定
# ========================================
external_dependencies:
  anthropic_api: enabled    # Claude API使用
  github_api: enabled       # GitHub連携
  aws_api: enabled          # AWS MCP統合
  starbose_llm: disabled    # Starbose LLM（ローカル）※TBA: 将来実装予定
  external_mcp: enabled     # 外部MCPサーバー

# ========================================
# GitHub設定
# ========================================
github:
  repository: "taskflow"
  owner: "yuto-kansoku"
  default_branch: "main"
  auto_label: true
  auto_assign: true
  draft_pr: true

# ========================================
# CCAGI Label System
# ========================================
labels:
  # ラベルカテゴリ（60ラベル体系）
  categories:
    - STATE       # 8: pending, analyzing, implementing, reviewing, done, blocked, failed, paused
    - AGENT       # 6: coordinator, codegen, review, issue, pr, deployment
    - PRIORITY    # 4: P0-Critical, P1-High, P2-Medium, P3-Low
    - TYPE        # 7: feature, bug, docs, refactor, test, architecture, deployment
    - SEVERITY    # 4: Sev.1-Critical, Sev.2-High, Sev.3-Medium, Sev.4-Low
    - PHASE       # 8: 1-requirements, 2-design, 3-planning, 4-implementation, 5-testing, 5.5-quality-gate, 6-documentation, 7-deployment
    - SPECIAL     # 7: security, cost-watch, dependencies, learning, experiment, wontfix, duplicate
    - TRIGGER     # 4: agent-execute, generate-report, deploy-staging, deploy-production
    - QUALITY     # 4: excellent, good, needs-improvement, poor
    - COMMUNITY   # 4: good-first-issue, help-wanted, question, discussion
    - HIERARCHY   # 4: root, parent, child, leaf

  # 自動ラベル推論
  auto_inference:
    enabled: true
    infer_type: true      # Issue内容からtypeを推論
    infer_phase: true     # コマンド・キーワードからphaseを推論
    infer_priority: true  # 緊急度キーワードからpriorityを推論

  # タスク分解フレームワーク
  task_decomposition:
    enabled: true
    levels:
      - epic     # hierarchy:root
      - phase    # hierarchy:parent
      - wave     # hierarchy:child
      - cycle    # hierarchy:leaf
    complexity:
      S: "1-2時間、単一ファイル"
      M: "半日〜1日、複数ファイル"
      L: "2-3日、アーキテクチャ変更"
      XL: "1週間以上、複数コンポーネント"

  # Epic Issue必須プロセス
  epic_requirements:
    as_is_to_be: true     # AS-IS/TO-BE分析必須
    gap_analysis: true    # ギャップ分析必須
    milestone: true       # マイルストーン設定必須
    due_date: true        # 期限設定必須

# ========================================
# プロジェクト構造
# ========================================
project:
  language: "TypeScript"
  framework: "Node.js"
  testing: "Vitest"
  package_manager: "npm"

  directories:
    src: "./src"
    agents: "./.claude/agents"
    commands: "./.claude/commands"
    docs: "./docs"

# ========================================
# エージェント設定
# ========================================
agents:
  enabled: true
  use_worktree: true
  worktree_base_path: ".worktrees"

  # CoordinatorAgent - タスク統括
  coordinator_agent:
    enabled: true
    dag_based: true
    parallel_execution: true
    max_parallel_tasks: 3
    uses_anthropic: true
    uses_github: true

  # CodeGenAgent - AI駆動コード生成
  codegen_agent:
    enabled: true
    model: "claude-opus-4-6"
    strict_mode: true
    auto_format: true
    auto_lint: true
    uses_anthropic: true

  # ReviewAgent - 品質評価
  review_agent:
    enabled: true
    min_score: 80
    static_analysis: true
    code_review: true
    uses_anthropic: true

  # PRAgent - PR自動作成
  pr_agent:
    enabled: true
    draft_mode: true
    auto_metrics: true
    conventional_commits: true
    uses_github: true

# ========================================
# 作業フロー
# ========================================
workflow:
  steps:
    - name: "タスク分解"
      agent: "CoordinatorAgent"
      required: true

    - name: "実装"
      agent: "CodeGenAgent"
      required: true

    - name: "品質チェック"
      agent: "ReviewAgent"
      required: true
      min_score: 80

    - name: "PR作成"
      agent: "PRAgent"
      required: true
      draft: true

# ========================================
# ログ・レポート
# ========================================
logging:
  level: "info"
  directory: "./logs"
  format: "json"

# ========================================
# 高度な設定
# ========================================
advanced:
  parallel_processing:
    enabled: true
    max_workers: 3

  cache:
    enabled: true
    directory: "./.ccagi-cache"
    ttl: "24h"

  retry:
    max_attempts: 3
    backoff: "exponential"
    initial_delay: "5s"

  timeout:
    code_generation: "30m"
    testing: "20m"
    security_scan: "15m"
    review: "10m"

# ========================================
# ドメイン・CC-Auth設定（Phase 1必須）
# ========================================
domain:
  dev_subdomain: "taskflow-dev.aidreams-factory.com"
  prod_subdomain: "taskflow.aidreams-factory.com"
  route53:
    account: "607520774686"
    hosted_zone: "aidreams-factory.com"

cc_auth:
  dev:
    account: "805673386383"
    user_pool_id: "ap-northeast-1_lSPtvbFS7"
    client_id: "5nm9g294deq3r8dl8qkq33eohp"
    callback_urls:
      - "http://localhost:3000/"
      - "http://localhost:3000/auth/callback"
      - "https://taskflow-dev.aidreams-factory.com/"
      - "https://taskflow-dev.aidreams-factory.com/auth/callback"
    logout_urls:
      - "http://localhost:3000/"
      - "http://localhost:3000/login"
      - "https://taskflow-dev.aidreams-factory.com/"
      - "https://taskflow-dev.aidreams-factory.com/login"
  prod:
    account: "661103479219"
    user_pool_id: "ap-northeast-1_z76s7mTve"
    client_id: "6qpglrhtneplr9jvfcq4jpnr7r"
    callback_urls:
      - "https://taskflow.aidreams-factory.com/"
      - "https://taskflow.aidreams-factory.com/auth/callback"
    logout_urls:
      - "https://taskflow.aidreams-factory.com/"
      - "https://taskflow.aidreams-factory.com/login"

# ========================================
# フィードバック管理設定
# ========================================
feedback:
  status_values:
    - pending
    - in_progress
    - applied
    - closed

  source_of_truth: "ssot_issue"

  sync:
    enabled: true
    direction: "bidirectional"
    auto_normalize: true

  local:
    directory: ".ai/feedback"
    file_pattern: "*.md"

# ========================================
# CCAGI SDK 仕様
# ========================================
sdk:
  version: "3.5.0"

  # コマンドシステム
  commands:
    source: "embedded"      # バイナリ埋め込み
    count: 97
    alias_dir: ".claude/commands"
    execution: "mcp"        # MCP経由実行

  # スキルシステム
  skills:
    source: "embedded"
    count: 47
    execution: "mcp"

  # MCPサーバー
  mcp:
    server: "ccagi-tools-server"
    tools:
      - skill_execute       # スキル/コマンド実行
      - skill_list          # 一覧取得
      - skill_info          # 詳細取得
      - agent_run           # エージェント実行
      - command_execute     # コマンド実行
      - command_list        # コマンド一覧
      - agent_list          # エージェント一覧
      - agents_summary      # サマリー取得
      - orchestrate_workflow # ワークフロー実行

  # エイリアスシステム
  alias:
    enabled: true
    directory: ".claude/commands"
    format: "markdown"      # エイリアスファイル形式
    size_per_file: "~400 bytes"
    total_size: "~40KB"     # 97コマンド合計
